apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: project1
  name: project1
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: project1
status:
  loadBalancer: {}