apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: neo87z
  name: neo87z
spec:
  ports:
  - port: 3009
    protocol: TCP
    targetPort: 3009
  selector:
    app: neo87z
status:
  loadBalancer: {}