apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: repo1done
  name: repo1done
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: repo1done
status:
  loadBalancer: {}